name: lists
description: A list of professors, cources and students.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  go_router: ^12.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  multi_dropdown: ^2.1.0
  path_provider: ^2.1.1

flutter_launcher_icons:
  image_path: "assets/images/lista.png"
  android: true # can specify file name here e.g. "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # use 'flutter pub get' and 'flutter pub run flutter_launcher_icons' to generate icon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
