name: calculator_app
description: A calculator that can handle fractions.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/images/icons8-calculator-100.png"
  android: true # can specify file name here e.g. "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # use 'flutter pub get' and 'flutter pub run flutter_launcher_icons' to generate icon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PixelifySans
      fonts:
        - asset: fonts/PixelifySans/static/PixelifySans-Regular.ttf
          weight: 400
        - asset: fonts/PixelifySans/static/PixelifySans-Medium.ttf
          weight: 500
        - asset: fonts/PixelifySans/static/PixelifySans-SemiBold.ttf
          weight: 600
        - asset: fonts/PixelifySans/static/PixelifySans-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: fonts/RobotoCondensed/RobotoCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/RobotoCondensed/RobotoCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/RobotoCondensed/RobotoCondensed-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Unifont
      fonts:
        - asset: fonts/Unifont/unifont-15.1.02.otf
